name: Generate Snake

on:
  # Automatically run every day at midnight
  schedule:
    - cron: "0 0 * * *"
  # Allows manual triggering
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Generate the snake animation
      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Commit and push the generated SVG files
      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add output/
          git commit -m "Generate contribution snake animation"
          git push